### ISSUE TITLE
Thaumonomicon Pages for next update

### ISSUE THREAD

**Issue by HellFirePvP** [makeoo/Gadomancy#21]
Hey Guys,

We're soon ready to release v1.0.3 of our mod and we - again - need YOUR help to write some entries for the Thaumonomicon.

**++SPOILER ALERT++ ++SPOILER ALERT++ ++SPOILER ALERT++**
If you don't want to get to know what's coming in the next update or if you want to research it on your own without getting informed about it here, please stop reading NOW. Otherwise you will be somewhat informed what's coming.
**++SPOILER ALERT++ ++SPOILER ALERT++ ++SPOILER ALERT++**

To each entry i'll provide some necessary information.

[New Golem Core - Basically it does what it says here, attacking things that attack you. Targeting is similiar to the Minecraft Wolf]
[Made of: Guard core, Boots of traveller, sword if zephyr]
tc.research_name.GADOMANCY.GOLEMCOREBODYGUARD=Golem Core: Bodyguard
tc.research_text.GADOMANCY.GOLEMCOREBODYGUARD=One does not simply attack my Master
gadomancy.research_page.GOLEMCOREBODYGUARD.1=Nothing to read here so far.

The rest of the researches are connected to the "Familiar" - Basically that's an item, if you wear it in the Bauble's Amulet slot, it spawns a Wispy-looking Familiar that's flying around you and attacking monsters in close range with low attack. Upgrades (further down) Increase damage, attack range and attack speed. However, please try to avoid writing the real numbers in there ;)
I hope the decriptions answer some questions about the content itself ;)

[Made of: Nitor, Primal charm, Salis mundus, mixed crystal clusters and the wisp-essence you want the familiar to have]
[Essentia needed: Praecantatio, Auram, essentia of the familiar's type]
tc.research_name.GADOMANCY.FAMILIAR=Familiar
tc.research_text.GADOMANCY.FAMILIAR=A arcane follower
gadomancy.research_page.FAMILIAR.1=Thanks to your deep research into Wisps and arcane flames you call 'Nitor' you think you may be able to create a being just like the Wisp. Using the same Ethereal Essence and Essentia you are able to define the base aspect of your Familiar. But that's not enough! You might be able to direct its movements and actions to defend yourself with it. However, making it attack players doesn't seem so easy and it seems a bit weak too.. Let's do something about that when the time comes...

[Attack increase from .5 hearts to 1 heart per attack]
[Made of: Amber, Magic tallow, wisp-essence of the familiar's type]
[Essentia needed: Praecantatio, Auram, essentia of the familiar's type]
tc.research_name.GADOMANCY.FAM_ATTACK_1=Attack Enhancement
tc.research_text.GADOMANCY.FAM_ATTACK_1=Increasing the damage
gadomancy.research_page.FAM_ATTACK_1.1=Nothing to read here so far.

[Attack increase from 1 heart to 2 hearts per attack]
[Made of: primal charm, mixed crystal cluster, void seeds, wisp-essence of the familiar's type]
[Essentia needed: Praecantatio, Auram, alienis, essentia of the familiar's type]
tc.research_name.GADOMANCY.FAM_ATTACK_2=Further Attack Enhancement
tc.research_text.GADOMANCY.FAM_ATTACK_2=What does the scouter say about its power level?
gadomancy.research_page.FAM_ATTACK_2.1=Nothing to read here so far.

[Attack increase from 2 hearst to 4 hearts per attack]
[Made of: 1x nether star, 1x primordial pearl, 2x ethereal bloom, wisp-essence of the familiar's type]
[Essentia needed: Praecantatio, Auram, telum, essentia of the familiar's type]
tc.research_name.GADOMANCY.FAM_ATTACK_3=Maximized Damage
tc.research_text.GADOMANCY.FAM_ATTACK_3=ITS OVER 9000!
gadomancy.research_page.FAM_ATTACK_3.1=Nothing to read here so far.

[Range increase from 5 to 8]
[Made of: Alumentum, void seeds, wisp-essence of the familiar's type]
[Essentia needed: Praecantatio, Auram, essentia of the familiar's type]
tc.research_name.GADOMANCY.FAM_RANGE_1=Range Enhancement
tc.research_text.GADOMANCY.FAM_RANGE_1=Attacking even further
gadomancy.research_page.FAM_RANGE_1.1=Nothing to read here so far.

[Attack speed from 1 attack per second to 2 attacks per sec]
[Made of: primordial pearl, primal wand focus, purifying bath salts, wisp-essence of the familiar's type]
[Essentia needed: Praecantatio, Auram, permutatio, essentia of the familiar's type]
tc.research_name.GADOMANCY.FAM_COOLDOWN_1=Attack-Speed Enhancement
tc.research_text.GADOMANCY.FAM_COOLDOWN_1=A scientific Railgun
gadomancy.research_page.FAM_COOLDOWN_1.1=Nothing to read here so far.

That's about it, if you'd like to help, just go ahead. If you need additional pages for text, just increment the last number, like second page of "gadomancy.research_page.FAM_COOLDOWN_1.1" would be "gadomancy.research_page.FAM_COOLDOWN_1.2" and so on...

Thanks in advance ;) ~HellFirePvP
# edit: for additional information, just comment on this issue with your questions ;)

**Comment by BBoldt** [comment]
Maybe @63502 wants to do these? :D

**Comment by 63502** [comment]
Definitely. :)

**Comment by 63502** [comment]
I have the entries for the new research done! :D

I have made suggestions, asked questions, and recommended a few edits along the way.

# 

[Made of: Guard core, Boots of traveller, sword if zephyr]
tc.research_name.GADOMANCY.GOLEMCOREBODYGUARD=Golem Core: Bodyguard
tc.research_text.GADOMANCY.GOLEMCOREBODYGUARD=One does not simply attack my Master
gadomancy.research_page.GOLEMCOREBODYGUARD.1=Guard Golems are all good and fine, but even with upgrades, they still don't understand how to protect their master specifically. Adding a few modifications to a Golem Core: Guard easily remedies this issue. A golem equipped with the Golem Core: Bodyguard will be smart enough to follow its master around in a manner similar to that of a tamed wolf.

Are there any other features I should mention here? Also, would a golem with this core target EXACTLY like a wolf, or would the player it still be able to specify what it can and can't attack by installing an order upgrade.

# 

I like the wisp like defender idea a lot, however I do feel that "Familiar" is  a slight misnomer. This charm, to me, has the feeling of an offensive protection charm rather than a separate creature entirely. It seems to be more closely related to an Amulet of Runic Shielding that has been altered so that it uses its magic charge to generate a small wisp like projection that attacks enemies, rather than forming a shield to block damage.

I have edited the recipe and the research text to show you what I mean. 
If you like my idea, I would recommend making this research dependent on the research for Runic Shields. Also, a new type of wisp for each different essentia type seems like a bit of a tall task, esspecially including  essentia types from other addons, perhaps one type for each Primal will suffice?Maybe a color changing upgrade?

I have written the upgrade researches so they can work with either one of the wisp familiar ideas.

[Made of: Mundane Amulet Nitor, Primal charm, Salis mundus, and any three Ethereal Essence]
[Essentia needed: Praecantatio, Auram, Potentia, Telum]
tc.research_name.GADOMANCY.FAMILIAR=Amulet of Ethereal Defense(just an example, subject to change)
tc.research_text.GADOMANCY.FAMILIAR=Runic.......... wisps?
gadomancy.research_page.FAMILIAR.1=Ethereal Essence seems to react quite strangely around runic shields. It hums, fluctuates, and even glows in a manner that seems similar to living wisps.
After some experimentation, you found that by altering the runes in an Amulet of Runic Shielding and infusing the amulet with some Ethereal Essence, you could make the amulet project an entity similar to a wisp. The projection mimics the behavior of wild wisps, attacking anything that gets to close to its source of magic.
The projected wisp replaces the amulet's ability to create a shield, and it cand only be maintained as long as the amulet is supplied with vis from a wand.
You notices that the wisp seems a bot weak; you think that you should find a way to remedy this...

[Attack increase from .5 hearts to 1 heart per attack]
[Made of: Amber, Magic tallow, wisp-essence of the familiar's type]
[Essentia needed: Praecantatio, Auram, essentia of the familiar's type]
tc.research_name.GADOMANCY.FAM_ATTACK_1=Attack Enhancement
tc.research_text.GADOMANCY.FAM_ATTACK_1=Increasing the damage
gadomancy.research_page.FAM_ATTACK_1.1=By concentrating more magic into the wisp, its attack power is effectively doubled.

[Attack increase from 1 heart to 2 hearts per attack]
[Made of: primal charm, mixed crystal cluster, void seeds, wisp-essence of the familiar's type]
[Essentia needed: Praecantatio, Auram, alienis, essentia of the familiar's type]
tc.research_name.GADOMANCY.FAM_ATTACK_2=Further Attack Enhancement
tc.research_text.GADOMANCY.FAM_ATTACK_2=What does the scouter say about its power level?
gadomancy.research_page.FAM_ATTACK_2.1=By adding eldritch energies and further concentrating the wisps internal magic, an even further doubling can be achieved. You occasionally hear strange whispering coming from the wisp, but the sound is so quiet that you don't think it will be an issue. (maybe get some temp warp from this?)

[Attack increase from 2 hearts to 4 hearts per attack]
[Made of: 1x nether star, 1x primordial pearl, 2x ethereal bloom, wisp-essence of the familiar's type]
[Essentia needed: Praecantatio, Auram, telum, essentia of the familiar's type]
tc.research_name.GADOMANCY.FAM_ATTACK_3=Maximized Damage
tc.research_text.GADOMANCY.FAM_ATTACK_3=ITS OVER 9000!
gadomancy.research_page.FAM_ATTACK_3.1= After observing the primordial pearl for some time, you think you can find a way to use it to enhance the wisp even further. By infusing the resonating energies of the pearl with the wisp, you found a way to double(maybe triple or quadruple would be more appropriate for a primordial pearl) its power. The nearly inaudible whispering has become far more pronounced, leaving you with an uneasy feeling...

[Range increase from 5 to 8]
[Made of: Alumentum, void seeds, wisp-essence of the familiar's type]
[Essentia needed: Praecantatio, Auram, essentia of the familiar's type]
tc.research_name.GADOMANCY.FAM_RANGE_1=Range Enhancement
tc.research_text.GADOMANCY.FAM_RANGE_1=Attacking even further
gadomancy.research_page.FAM_RANGE_1.1=By enhancing the wisps sensitivity to external influence, you can slightly increasing its range.

[Attack speed from 1 attack per second to 2 attacks per sec]
[Made of: primordial pearl, primal wand focus, purifying bath salts, wisp-essence of the familiar's type]
[Essentia needed: Praecantatio, Auram, permutatio, essentia of the familiar's type]
tc.research_name.GADOMANCY.FAM_COOLDOWN_1=Attack-Speed Enhancement
tc.research_text.GADOMANCY.FAM_COOLDOWN_1=A scientific Railgun
gadomancy.research_page.FAM_COOLDOWN_1.1=The resonance of the primordial pearl has proven useful in more than one way. Combining the pearl and a primal wand focus with the wisp seems to change its frequencies drastically. The enhanced wisp attacks twice as fast as before(again, maybe triple speed would be more appropriate for the use of a primordial pearl?)

Regarding the two primordial pearl upgrades, perhaps there could be a restriction preventing them both from being applied to a wisp at the same time?

# 

Please do tell me if there is anything that I missed or misinterpreted.

Thanks,
     Redcreeper63502

**Comment by HellFirePvP** [comment]
Please don't ask me how the Bodyguard core works exactly. That was something @makeoo implemented. I guess he has to answer you here.

---

The main Idea behind the Familiar is an offensive damage support. I can see where your idea of a defensive-support-ish Wisp comes from, but the Familiar is offensive oriented, because thaumcraft already includes Runic shielding as the defensive option - At least that was my idea behind it when i created the Familiar. In addition to that the Familiar looks like a Wisp in the inventory and around you so i'd like to keep its aggressive nature - only now it's directed against the mobs instead of you.

However, i will stay with it being an aggressive ethereal creature you can "equip" as an active damage-support. Also, ingame the Familiar looks like a Wisp flying around you~

I guess i can add it that the familiar gives you temp warp and maybe some other stuff occasionally when it's Attack is "level 2" or higher - thanks for the suggestion :grin:

The Familiar - when fully upgraded - is already quite strong. doing 8 damage (4 hearts) 2 times a second in an 8 block radius (11 blocks if the mob targeted you once) - that's a lot. If you could take unlimited damage - hypothetically speaking; or even practially speaking if you have sth. like 'Draconic Evolution' in your modpack - a fully upgraded familiar can take out a Eldrich-Maze boss all on its own. That's quite some damage i guess. The familiar should get higher upgradeable the more you progress in playing Thaumcraft. Stages are like: Magic Tallow -> Void seeds -> Primordial pearl - Well not that great balanced along the way of progression, but considering that the last upgrades do provide alot of damage increase, it feels ok to me. By invesing alot in the Familiar you should get something powerful. The Familiar should also be something you may be able to obtain early in your Thaumcraft journey, but it should still be relevant even if you cleared the Eldrich maze for the first time. And there will be more Familiar upgrades when me and makeo added some more content. Just wait~ :P

The familiar-type based effects are something i already thought of, but that will take its time to think about what each type should do to the environment. It will not be included yet in the upcoming release.

Anyway: :sparkles: thank you for creating those entries. :sparkles: MUCH APPRECIATED :sparkles:
And of course stay tuned - we'll release the next update within the next days! (i think -_-")

**Comment by HellFirePvP** [comment]
Oh and of course the Familiar/Wisp has the color of the aspect it was made of. Just the same color as the aspects themselves - you'll see soon^^

**Comment by BBoldt** [comment]
I agree with @63502 about the familiar in some respects, mostly because I don't like it being called "familiar". Witchery has familiars, and those are something else entirely.

You could keep the same exact creature without calling it a "familiar".

**Comment by 63502** [comment]
I think I understand the familiar idea a bit better. I was just a bit more concerned about how it would be bound to the player since, after all, a ghostly piece of semi incorporeal magic is somewhat difficult to carry around. An amulet could just act as a container when the wisp isn't equipped, just for a little bit of realism.

And yes BBoldt, that was my other concern.

**Comment by 63502** [comment]
Either way, I cant wait to see the next update.

I AM GOING TO SEE MY OWN WRITING IN THE THAUMONOMICON! SO HYPED! XD

**Comment by HellFirePvP** [comment]
Since we have to work with most of the TC Addons to make it compatible with them, we also came across Thaumic Horizon's "Familiars" - Not sure what they are. Only cats that recharge your held wand. wtf. :P

Well... The Idea of the Familiars didn't come from Witchery though..

Any ideas for other names?

#Edit: i'm afraid i never really played Witchery..

**Comment by 63502** [comment]
Yes... and the TH familiars resemble something out of the manga Soul Eater :/

As for names off the top of my head,
Sealed Wisp
Ethereal Sentinel
Sentinel Wisp
Watcher
Sentinal....

There aren't many other names i can think of that would fit a wisp. 
Since a wisp is essentially just an animated collection of magic, I don't think calling it a companion or a pet would be accurate.

**Comment by BBoldt** [comment]
Since it's not for defense and more for offense, maybe something more agressive?
- Assailant
- Invader
- Raider
- Blitzer
- Striker

**Comment by HellFirePvP** [comment]
@BBoldt I don't really know, since it'll lose its "magical side" when naming it something like "Invader"... More aggressive naming would work, but in a more "magic" way i guess.. #Edit: it also stays near you all the time, so its not invading or being that aggressive really... :P _just sayin'_ ^^

@63502 Not easy to find someting appropiate i guess.

How important are Familiars in Wichery? Are they some non-important side-content or something you have to have in order to progress?

I don't really want to part with the name "Familiar" though... ^^

I will discuss this with makeo and we will see if we rename it or not. But thanks for your opinions on that~

**Comment by 63502** [comment]
Familiars are VERY important to a large and central section of witchery. More specifics on that are here(https://sites.google.com/site/witcherymod/familiars).

As for the name of the wisp, maybe just calling it an "Ethereal Familiar" would make the name more specific to the creature? Just calling it "Familiar" is a bit vague.

**Comment by BBoldt** [comment]
Ethereal Familiar would work

**Comment by HellFirePvP** [comment]
I'll rename it to "Ethereal Familiar" then~

(I should really play Witchery one day...)

**Comment by 63502** [comment]
Definitely. Witchery has so much content it's ridiculous. Not only that, but the mod doesn't have a single central path, so you can decide what you want to do. 

I use it all the time. :)

**Comment by makeo** [comment]
Currently the golem core: bodyguard can't be upgraded using a order upgrade. I'll add it in the next update :) But if you right click the golem he will look at the ground and no longer attack or follow you

**Comment by BBoldt** [comment]
Sort of unrelated, but if you guys need any textures, I can do textures too.

**Comment by HellFirePvP** [comment]
Well @BBoldt if you want to, we still need an icon for the Golem Core: Break :sweat_smile:
:sparkles: Something like a little pickaxe would be awesome :sparkles:
