### ISSUE TITLE
Ethereal Familiar Suggestions

### ISSUE THREAD

**Issue by Dayyer1** [makeoo/Gadomancy#25]
I thought the Ethereal Familiar was a GREAT idea, first of all, but I have some comments, if that's ok:
-although it seemed a more expensive item, I feel that after all the upgrades it was still too powerful somehow.
-I thought the fact that the Familiars attacked mobs that were just conveniently close enough sort of lessened the point of monster hunting or dungeons. What if they only attacked if you were attacked and also when you were the attacker? Maybe that could be configured or something?
-Speaking of configuration, what if you could only have certain upgrades and more upgrades on a Familiar? The catch would be that some upgrades can't go together, like how Sharpness and Smite can't combine.

Sorry for typing so much.
The thing is that I am trying to create my own Thaumcraft mod, but I'm still reading the programming books. I have sooooo many ideas but I can't integrate them yet. (It's especially frustrating though that Thaumcraft 5 is now out. The question is if I should make an addon for v5 or v4? What books should I be reading? Etc.)

If you survived through all that text, thank you. Sorry that I can't really help with the actual coding. I only have ideas.

**Comment by HellFirePvP** [comment]
First of all thanks for the great and constructive feedback!

Well, some guys are saying the ethereal familiar isn't strong enough and they prefer defensive choices more - and you happen to say the same thing as me or makeo. A fully upgraded ethereal familiar is stronger than we actually wanted it to be since its just there attacking everything that comes close to you.

First of all we're still thinking about balancing and changing the ethereal familiar. One thing that came to my mind was more or less exactly what you said - it does only attack whatever attacks its owner. One problem arises doing this: What if the attacker doesn't attack the entity directly? Speaking of arrows, other projectiles, (TC only) wand foci, .. or just saying "other mods we don't know yet" - Problem is: We don't know what mods are out there and how they are attacking the player. Of course we could go the simple way and access the mob that attacked the player last and sum all attacking mobs up. The problem are again mods that don't attack the "correct way" so we more or less can't see when or how they do damage and if or if no other mob was involved in that.

HOWEVER, we're looking into that issue and try to find something less op than "attacking everything that's around you".

We didn't yet think about upgrade interaction like "upgrade X can't be applied together with upgrade Y" and we don't have any plans for that at the moment. One simple problem with this is: What !useful! upgrades should we include? Upgrades that actually make sense and are something you would drop the attack damage or range or speed upgrade(s) for.

To yourself, learning Java is something that takes time and you're most efficient in terms of learning if you actually DO something instead of reading how its done in a book. Writing mods is **not** something Java beginners should do because the base-code (Minecraft & Minecraft Forge in that case) you are writing on is not 100% stable and may create errors where you never find yourself involved.

Just one example of what happened to me yesterday: http://pastebin.com/61PbuDsX - took me about 10 minutes to find the actual problem: I tried to place a Block (code-wise). The chunk where the block was in was not loaded yet so minecraft had to load it. The chunk didn't exist before so it had to be created. All worldGenerators have a chance of modifying the newly created chunk - also thaumcraft. Thaumcraft tried to (more or less) create the exact same thing that i was trying to create. That way it accessed the same ArrayList as i did and it got modifyed by thaumcraft -> ConcurrentModificationException. Errors are not always easy to find, fix or explain why they happen. It takes a lot of knowledge of the programm you are modding (in that case Minecraft via Minecraft Forge) and in order to focus on gaining knowledge how minecraft works you have to have good knowledge on how Java works and what method or class does and what they are special for. Example: a HashMap, a LinkedHashMap and a ConcurrentHashMap are basically all maps. You can do more or less the same thing with them, but still they are different in the ways they work - And minecraft does make use of that at some places. Minecraft is also built with Frontend and Backend systems (aka Client & Server) where both of the systems are exchanging and synchronizing data - you have to have control over what's happening server-side and what's happening client-side and what data you have to synchronize and when. And that's only a small part of what you have to pay attention to when developing a minecraft mod.

So Minecraft modding is probably not the best to start with.. Try developing some smaller projects first and don't just read books. I personally never read a book about Java or anything minecraft development related.

#WallOfText #IWon'tReadThatShitAgain #FinallyDoneWriting

**Comment by Dayyer1** [comment]
Thank you for the advice - for one thing I've had no idea how to start the coding or anything. 

For the Ethereal Familiar, I meant just small additions like an upgrade that takes life from other mobs, or when a mob is hit some debuff is applied. I see what you mean by useful though, like the current ones could be applied no matter what, these would just be little differences, minor things.

Do you have any suggestions of small projects I could do, or something of the like? Something I could do to get started?

**Comment by Shadows-of-Fire** [comment]
@HellFirePvP Still haven't gotten around to updating the mod, will later today to get a better idea of this new thing that has everyone up in arms, but probably don't make it attack everything around you. I believe there's a mob attribute that declares whether it is hostile or not, can't you use that to decide what to attack? Also, if you really want to nerf offensive power without killing the concept, drop the attack speed.

@Dayyer1 [Codecademy](https://www.codecademy.com/learn/learn-java) recently launched a java course, I think their methods are a bit strange, but it certainly helps get the point across.

**Comment by Dayyer1** [comment]
Thank you @Shadows-of-Fire, I will look into it.
...also, the thing that is in the update is really cool, I think.

**Comment by HellFirePvP** [comment]
@Shadows-of-Fire It does only attack mobs not everything around you - sorry i messed up with words there.. -_-" And it's not that i want to directly nerf the power of it though.

**Comment by HellFirePvP** [comment]
Just to drop that here: The Ethereal Familiar attacking AI has changed for the next update.

For further details please wait for the update notes

~Closed~
