### ISSUE TITLE
Missing pre-requisites

### ISSUE THREAD

**Issue by Alchimous** [makeoo/Gadomancy#27]
Not a major issue, but the etheral familiar, despite being an infusion recipe, does not require infusion to unlock. Similarly, mirrored jars can be researched with only warded jars unlocked, not void or either type of mirror.

**Comment by HellFirePvP** [comment]
Yes i talked about that with makeo before. The reason why we didn't include the infusion as pre-requisite for some researches so far is rather simple: We couldn't fit it in our thaumonomicon page the way we wanted it and because of that we left out some pre-requisites that are needed for some items.

But don't worry i'm already working on restructuring the page again and i'm trying to find some space for them.

**Comment by HellFirePvP** [comment]
Fixed - will be included next update

~Closed~
