### ISSUE TITLE
Crash On New World

### ISSUE THREAD

**Issue by thegreatersea** [makeoo/Gadomancy#33]
Gadomancy version: 1.0.5
Forge: 1558
Crash report: http://paste.ee/p/PFVyY

The game loads up normally, but when I try to create a new world, the above crash happens. Most of the error is gibberish to me, but there is mention of the methods involved in gadomancy's special outer lands.

**Comment by HellFirePvP** [comment]
That error might be the result of using a different library than we did when we compiled the mod.

Trying to resolve the issue which library it is and how that error was created. Thanks for submitting it.

I cannot provide a solution right now though, because i'm not exactly sure what part of your installation is different and why this bug happens. I'll comment here once we found out something and/or if we can provide a viable solution.

**Comment by HellFirePvP** [comment]
We could not recreate the issue - even with different forge versions in use.

We conclude that the issue is created by your modpack.

So please tell us what modpack you're using or if you don't want to, please remove mods one by one until the issue is fixxed and let us know which mod causes the issue.

Until then i'm afraid we can't do anything.

**Comment by HellFirePvP** [comment]
Closed, because no answer. If you can provide the necessary information at some point, feel free to reopen this issue and provide the information.
