### ISSUE TITLE
Sticky void jars behave wrong

### ISSUE THREAD

**Issue by midorlo** [makeoo/Gadomancy#48]
I encountered two concept breaking bugs while playing around with sticky jars:
- TC Golems do not dump essentia in sticky Void Jars placed upside down. The golems do place essentia into them if there is enough space though. 
- Picking up a sticky void jar yields a sticky regular jar.  

Enviroment:
Current stables of Java8, Forge, TC, Gadomancy;

**Comment by HellFirePvP** [comment]
We'll look into that and fix it for 1.0.7 or we might prepare a hotfix version for that since its a kind of big bug :P

I also saw your comment on the curse site and yea we're always happy to see some suggestions. We'll look into that and see what we do about it. Can't promise anything though ;)

**Comment by midorlo** [comment]
Not to be impatient but will the fix happen in days, weeks or months? That kinda decides if I'll rebuild a considerably big (~10h) storage system.

**Comment by HellFirePvP** [comment]
I asked makeo to answer you since he wrote the jar stuff - however it seems like he forgot it~ Well nevermind.

The thing is, i and makeo have tests for university the next few weeks, so we really can't "waste" any time not learning, so an update containing bug fixxes and new features is not possible atm. However, once tests are finished and all that stuff is done, we're obviously continuing to fix and add new stuff to the mod.

So, i'm afraid to say that, but there won't be an update the next week(s)

**Comment by midorlo** [comment]
Sounds sane to me. Good luck on the exams!

**Comment by Barhandar** [comment]
Add a third one to that: sideways sticky void jars do not accept essentia when full, essentially meaning they're _utterly useless_ as void jars, but they still provide suction, unlike regular jars, clogging buffer-spines.

**Comment by HellFirePvP** [comment]
Breaking a sticky void jar will now yield a sticky void jar again. FIXXED
When a sticky void is full, it will still accept essentia now. FIXXED
A golem still can't put stuff into a full sticky void jar. That's beyond fixxing in 1.7 TC4.2. Might see a fix in 1.8 TC5, but no guarantee on that. NOT FIXXED

~Closed
