### ISSUE TITLE
increased luck enchant persistance "0:00 duration". Prevents display of other effects to the user.

### ISSUE THREAD

**Issue by usafphoenix** [makeoo/Gadomancy#49]
got a issue that's hard to explain. a little while into playing a map with gadomancy on a private pack i start to have an enchant "increased luck" with duration "0:00" that prevents other effects (positive or negative) from displaying in inventory screen as they should normally. 
it persists indefinitely.
removed the mod and had to delete NBT tags for the effect to reload world. 
so like if i have gadomancy installed and i fight a witch, or use a water-breathing potion or regen potion, the durations of those (or any info at all does not display)

**Comment by usafphoenix** [comment]
dumped potion effects and enchants and forge assigned 'gadomancy.increased luck to id 0. i can try changing it to a different id if id 0 is supposed to remain unused for whatever reason. or do a fresh install with just thaumcraft, gadomancy or whatever to try and help figure out what's causing either A) the effect to be triggered without a duration or B) why other potion effects are being prevented from displaying once increased luck takes effect.
I want to say the most likely cause is that it isn't properly unloading from memory or clearing out after the timer runs out.

**Comment by HellFirePvP** [comment]
Well the potion effect itself behaves like any other potion effect.. - so when it runs out it should actually remove itself, because we don't anything about that.

My first thought would be a id conflict.. by default, gadomancy tries to find a free id and uses it as the ID for our potion effects. That might cause issues in bigger modpacks, that's why you can, and should, specify fixed potion and enchantment id's in the config.

If forge says it assigned it to ID 0 that sounds like an id conflict too... Did that only start when actually getting the "Increased Luck" with the Aura Pylon or is it just any potion effect will give you "Increased Luck" - if so, that might be an id conflict.

**Comment by usafphoenix** [comment]
i never even began work with gadomancy. got the enchant about an hour into playing a new world. looks like the very first time i get a potion enchant, it displays "increased luck 0:00"

**Comment by usafphoenix** [comment]
also, don't know if i mentioned it in original post, but attempting "effect usafpheonix clear" returns error stating i had no effects. but NBT edit and my screen stated i had two. one being increased luck and the other being one from a witch...which wasn't being displayed on screen so not sure if it was wither or poison

**Comment by HellFirePvP** [comment]
Well as i said it might be an ID conflict.

Anyway, what modpack are you using to cause this? With an environment containing only Thaumcraft, Automagy, Gadomancy, Mystcraft, Waila and NEI it works fine. Additionally it works fine in Regrowth.

**Comment by ArmouredDrood** [comment]
The "increased luck", or PotionMiningLuck, seems to auto-assign itself to id 0, according to NEI's dump. I gave the potions set IDs, and removed the mod PotionIDHelper, and that solved the problem.
Am using a custom pack.

**Comment by Shadows-of-Fire** [comment]
Leaving Gadomancy's potions on Auto Assign creates issues since forge doesn't seem to auto assign potions very well (same issue with TC4's auto assigns). Set them manually, and set all ID's in your pack manually. Avoid using PotionIDHelper, as it breaks anything that extends upon the potion system to add HUD's (AM2, StatusEffectHUD).

**Comment by usafphoenix** [comment]
THANKYOU. Had no idea poitonIDHelper broke AM2's HUD (was a huge problem in
my pack as i was working with AM2 and gadomancy. i thought potionID
conflicts were the problem (or would be) so i added the mod to help locate
collisions but, yeah; issues :(
thanks a billion!

**Comment by HellFirePvP** [comment]
Well. fixxed.

CLOSED
