### ISSUE TITLE
Grave of the Voidwalkers waits 15ish minutes before teleporting

### ISSUE THREAD

**Issue by tprussak** [makeoo/Gadomancy#53]
For some reason the Grave of the Voidwalkers does nothing when you try to enter the portal, but then 10-15 minutes later it suddenly teleports you into the outer lands.

**Comment by HellFirePvP** [comment]
Sorry for the late reply - i can not imagine the portal having such awkward behavior. Assuming the server behind it runs stable and you do have all necessary research done before you entered the portal, i cannot see an option for this to happen. Can you reproduce the issue? And if so, in which modpack does it appear? Is there any message in the console that could relate to this behavior? Any error or other message?

**Comment by tprussak** [comment]
It has happened twice now, the third time there was an internal server error and the portal dissapeared. This is on the Nuts and Bolts modpack, on the Breakin' Blocks server.

**Comment by HellFirePvP** [comment]
Ok, i'm gonna look into it and see what i can find out.

**Comment by HellFirePvP** [comment]
Talked to Saereth and tried to pin down the issue.

To me the issue is kind of familiar, but me and makeo thought we fixxed that some time ago. However, i don't have a solution for it now, so i cannot provide any solution other than: "don't do that" :/

I'll see if i can find anything to fix the issue.. i'll be sure to inform you guys once there is a working fix for the issue.

**Comment by HellFirePvP** [comment]
We did some new iterations over the problem and... well we guess we fixxed it? At least we're kinda confident... soo.. FIXXED next version.

CLOSED
