### ISSUE TITLE
Gadomancy mod item.null.name with ID -1

### ISSUE THREAD

**Issue by 3mia** [makeoo/Gadomancy#60]
Hello,

I would like to report/ask to take a look at golem recipes in NEI, they're in the last recipe page and they're called item.null.name with ID -1. when I click on them I get crash, is there a way to remove them from recipe list?

**Comment by Shadows-of-Fire** [comment]
You can disable individual items using the item subsets feature of nei.  But I do believe that this issue was fixed.  Is your gadomancy up to date?

**Comment by 3mia** [comment]
Gadomancy version is 1.0.6.3. There's no item.null.name in subsets :/

**Comment by Shadows-of-Fire** [comment]
Previously this was an issue with thaumic horizions 1.1.9, but it was fixed in gadomancy 1.0.5, so I'm not sure what's happening.

**Comment by HellFirePvP** [comment]
We were sure to remove the bugs with the golem -1 stuff from NEI with version 1.0.4 or 1.0.5 as @Shadows-of-Fire mentioned before, so i'm kindof clueless at the moment why this happens.

Does it also happen to you if you only run Gadomancy together with Thaumcraft or only in a modpack environment?

**Comment by 3mia** [comment]
I have over 50 mods in my modpack and only when I add gadomancy these null items appears

**Comment by HellFirePvP** [comment]
Well we mess around with golems quite a bit so we faced this kind of issue before, but we thought it would be fixxed since we received feedback that those bug-items are gone.. Soooo... ugh.

I kindof have the suspicion that this error isn't necessarily coming from our mod, but happens in connection of our mod and somebody else's mod...

So, is your pack somewhere publicly available? If not and you're still working on the modpack i'd ask you to remove a mod one by one and see when those bug items disappear. Then we're able to figure out what's causing it...

**Comment by 3mia** [comment]
Modpack is not currently available anywhere I'm still working on it and I want it to be as much bug/crash free as possible. I will try to check which thaumcraft addon cause this issue and I will reply shortly

**Comment by HellFirePvP** [comment]
I wonder.. it could be a thaumcraft addon or some NEI addon - those seem most reasonable to me..

**Comment by 3mia** [comment]
The problem is only between thaumcraft and gadomancy. So basically I ran fresh game with only thaumcraft, gadomancy and not enough item mods, and these null items were in my recipes list... I tried to change config properties in every of these mods but didn't worked :/

**Comment by 3mia** [comment]
Is it possible for you to check if you're facing the same problem? I use thaumcraft 4.2.3.5 and gadomancy 1.0.6.3

**Comment by HellFirePvP** [comment]
I'll check it up in an hour or so if that's ok for you, i'm not at home atm.

**Comment by 3mia** [comment]
Cool, thank you :)

**Comment by HellFirePvP** [comment]
Confirming issue. Working on a fix.

**Comment by 3mia** [comment]
Thanks for the effort @HellFirePvP

**Comment by 3mia** [comment]
Any news?

**Comment by HellFirePvP** [comment]
1. I don't have the time to work on a fix right now since i have a 1 hour presentation at university tomorrow, and
2. I don't know when we're actually doing the next version update - however we'll release at least 1 more 1.7.10 version before updating to 1.8 (or rather 1.9 if and when TC updates) (depends on @makeoo too _cough_)

**Comment by HellFirePvP** [comment]
Since the next version of Gadomancy will now come up kinda soon, i looked over this again and i have to say i don't know what those items are or rather what they are, how NEI finds them or where exactly they come from. Not too sure if i can add a fix.

**Comment by Shadows-of-Fire** [comment]
They're golem placers that don't techncally exist. They range from Item ID's -1 meta 0 to -1 meta 8, and cannot be referenced with minetwealer due to having modid null.

**Comment by HellFirePvP** [comment]
I wonder why they're even there. From what i guess they're the "old" TC golem placers that got removed because we're overwriting them.... ugh.. accessing them will be pain xP

**Comment by HellFirePvP** [comment]
So... i fixxed it, but i don't really like the fix. So, well. it works i guess.

CLOSED - FIXXED
