### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by ConsiliumB** [makeoo/Gadomancy#70]
When attempting to use a wand on a Crystal Cluster with an Aura Core dropped next to it, every client within a chunk or so crashes every time. It might be our fault for adding lots of mods, since no-one else seems to have reported this issue, but the log seemed to indicate Gadomancy specifically

Crashlog: http://pastebin.com/5hTQniyS

**Comment by HellFirePvP** [comment]
I guess you're rightclicking the crystal cluster yourself rather than having anything else rightclicking it?

One appropiate, yet time consuming, way to find out where the problem comes from, would be removing one mod after another to see if the crash happens even if only Gadomancy is installed - which i kindof doubt tbh. - or to see which mod interaction causes this. Howeveri guess that's something you don't really want to spend your day on.

I'll look into it and see what i can find out.

**Comment by HellFirePvP** [comment]
I cannot reproduce the crash in any way, i'm sorry.

If you happen to find out which mod interaction causes this, please provide more information then. For now, i can't do much.

**Comment by Dream-Master** [comment]
@HellFirePvP I got this on the server. Single Player works just fine. Fastcraft are in the crash log too.

My client crash:
https://gist.github.com/Dream-Master/23dfb56c0ebdbc3071c74c87203e7165

Server log says this:

```
[12:34:20 INFO]: DreamMasterXXL lost connection: Internal Exception: java.io.IOException: Connection reset by peer
>
``
```

**Comment by Dream-Master** [comment]
I can't login get every time the same crash.

**Comment by HellFirePvP** [comment]
This error does seem familiar yes, i wasn't really able to narrow down this issue, but i guess i'm gotta try harder then. I do suspect a mod interaction to cause this. i'll see to it again and inform you here then.

**Comment by Dream-Master** [comment]
Ok thanks. After  three crashes I can login. The core is ready.

**Comment by HellFirePvP** [comment]
Ok, i do have little to no success with that issue or any attempt to reproduce it.. Was Gadomancy added to the pack/world after the world was already created?

My suspicion would be some sort of id conflict between server and client, whereas the server spawns an auracore entity and the client "undestands" it as our fakeplayer entity that never actually should get spawned and thus should never ever get rendered...

**Comment by Dream-Master** [comment]
Yes we add Gadomancy in an existing world. Item Ids cant change via config so what i can do or test?

**Comment by Shadows-of-Fire** [comment]
If what @HellFirePvP thinks is the cause is accurate, I've seen this before...  It's specifically a server client interaction issue, but not Gadomancy's afaik.  Some mod isnt registering an entity on Dedicated Server environments, so the ids are shifted around. Usually it doesnt effect this, but adding new entity ids (new mods) to sn existing world would cause this.

**Comment by Dream-Master** [comment]
So nothing i can do here with a old world ?

**Comment by Shadows-of-Fire** [comment]
It might also be more complicated than that... but theres no way to check other than intensive binary removal.

**Comment by Technus** [comment]
Any one tried remotely WorldEdit it out with //pos1 #,#,# //pos2 #,#,# //set 0?

**Comment by HellFirePvP** [comment]
Discussing that with @Shadows-of-Fire it seems that there's an Entity ID mismatch between server and client. So basically if the server spawns the EntityAuraCore, it'll send the type ID for that entity over to the client, which is the id for the fakeplayer on the client, which then... well. leads to this error.

Other than that i don't really know what would cause this.

How to test this? Well i'm not sure if you can print the assigned entity id's from the registry to log? If there is something like that available, you might want to do that on client and on serverside and compare the results.

**Comment by Dream-Master** [comment]
Sure if you implement a error log function I can test it and send you the logfile.

**Comment by Dream-Master** [comment]
@HellFirePvP 
ok is there a way to change the Entity ID ?
